
language: objective-c
osx_image: xcode12

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:
    - env
    - locale
    - gem install xcpretty --no-document --quiet
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail

    - echo Build the framework
    - xcodebuild clean build -scheme 'libvmaf' -sdk macosx -configuration Debug | xcpretty -c
    - xcodebuild clean build -scheme 'libvmaf' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
    - xcodebuild clean build -scheme 'libvmaf' -sdk appletvsimulator -configuration Debug | xcpretty -c
    - xcodebuild clean build -scheme 'libvmaf' -sdk watchsimulator -configuration Debug | xcpretty -c

    - echo Build the example app
    - xcodebuild build -scheme 'libvmafExample' -sdk macosx -configuration Debug | xcpretty -c