/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ARCH_X86 0

#define ARCH_X86_32 0

#define ARCH_X86_64 0

#define HAVE_ASM 0

#define HAVE_AVX512 0

#define PREFIX 1

#define VMAF_BUILT_IN_MODELS 1

#define VMAF_FLOAT_FEATURES 0

